jobs:

  ###################################
  # runCI job to update the image tag
  ###################################
  - name: deploy-ecs-multi-env_runCI
    type: runCI
    flags:
      - deploy-ecs-multi-env
    steps:
      - OUT: deploy-ecs-multi-env-image

  ######################################
  # Two parallel environments
  ######################################

  - name: deploy-ecs-multi-env-manifest-1
    type: manifest
    flags:
      - deploy-ecs-multi-env
    steps:
      - IN: deploy-ecs-multi-env-image

  - name: deploy-ecs-multi-env-bluedeploy
    type: deploy
    flags:
      - deploy-ecs-multi-env
    steps:
      - IN: deploy-ecs-multi-env-manifest-1
      - IN: deploy-ecs-multi-env-bluecluster

  - name: deploy-ecs-multi-env-greendeploy
    type: deploy
    flags:
      - deploy-ecs-multi-env
    steps:
      - IN: deploy-ecs-multi-env-manifest-1
      - IN: deploy-ecs-multi-env-greencluster


  ########################################
  # Two serial environments
  ########################################

  - name: deploy-ecs-multi-env-manifest-2
    type: manifest
    flags:
      - deploy-ecs-multi-env
    steps:
      - IN: deploy-ecs-multi-env-image

  - name: deploy-ecs-multi-env-betadeploy
    type: deploy
    flags:
      - deploy-ecs-multi-env
    steps:
      # - IN: deploy-ecs-multi-env-betaopts
      - IN: deploy-ecs-multi-env-manifest-2
      - IN: deploy-ecs-multi-env-betacluster

  - name: deploy-ecs-multi-env-proddeploy
    type: deploy
    flags:
      - deploy-ecs-multi-env
    steps:
      # - IN: deploy-ecs-multi-env-prodopts
      - IN: deploy-ecs-multi-env-betadeploy
      - IN: deploy-ecs-multi-env-prodcluster
